config/routes.rb
Rails.application.routes.draw do
  get 'blocks/destroy'

  get 'posts/new'

  get 'users/show'

  get 'users/index'

  devise_for :users
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  root to: "static_pages#home"
  get '/users/:id', :to => 'users#show', :as => :user
  get '/posts/:id', :to => 'posts#show', :as => :post
  resources :posts, only: [:create, :destroy, :new]

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :post
  has_many :comments#, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :block
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :blocks, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  accepts_nested_attributes_for :blocks,:reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments#, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?  
  
  # Confirms a logged-in user.
    def logged_in_user
      unless user_signed_in?
        flash[:danger] = "Please log in."
        redirect_to new_session_path(:user)
      end
    end

  protected

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) << :name << :posts
	    devise_parameter_sanitizer.for(:account_update) << :name << :posts
	  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController

  def destroy
  	if @block.comments
  		@block.comments.delete_all
  	end
  	@block.destroy
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
  	
  end

  def destroy

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy, :new]
before_action :correct_user,   only: :destroy
  def create
    if @post = current_user.posts.create(post_params)
      flash[:success] = "Post created!"
      redirect_to post_path(@post)
    else
      render 'static_pages/home'
  	end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  def new
    @post = Post.new(params[:post])
    5.times { @post.blocks.build }
    @blno = 5;
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  	def post_params
      params.require(:post).permit(:content,blocks_attributes: [:id,:title,:post_id,:_destroy])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@posts = Post.all.limit(30)
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! , only: :show
  before_action :authenticate_user! , only: :show
  
  def show
  	@user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @post = current_user.posts.build
  end

  def index
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "HMC"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blocks/_block.html.erb
<div class="box">
  <h1 align="center"> <%= block.title %> </h1>
</div>

app/views/blocks/destroy.html.erb
<h1>Blocks#destroy</h1>
<p>Find me in app/views/blocks/destroy.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer" style="text-align:center">
	<p style="font-family:Harlow Solid Italic;color:#D3D3D3;font-size:36px;">HelpMeChoose</p>
	<small>
		A Nitin, Sarthak, and Rounaq Production<br/>
	<%= link_to "About",   about_path %> | <%= link_to "Contact", contact_path %> | <a class="back-to-top " href="#" title="Top">Top of Page</a>
    </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "HelpMeChoose", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if user_signed_in? %>
          <li style="font-weight:bold;color:white;"><%= link_to "New Post", new_post_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_session_path(:user) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= render 'layouts/messages' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= link_to post.content,post_path %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user==post.user %>
      <%= link_to "delete", post, method: :delete,data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/posts/_postbox.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." ,id: "new-post-text"%>
  </div>
  <%= f.submit "Post", class: "btn btn-primary",id: "new-post-button" %>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<div class="container">
	<h1> Create new post </h1>
</div>
<div class="container">
	<%= form_for @post do |f| %>
	<%= f.text_field :content ,placeholder: "Enter Poll Name"%>  
	<div class="box-group">
	<%= f.fields_for :blocks do |builder| %>
	  <div class="box">
		  <h1 align="center"> Block </h1>
		  <%= builder.label :title, "Comparator"%>
		  <%= builder.text_field :title %>
		  <%= builder.hidden_field :_destroy %>
		  <%= link_to "remove","#",onclick: "remove_block(this)",class: "btn btn-sm btn-danger"%>
	  </div>
	<% end %>
	</div>
	<br/>
	<br/>
	<%= f.submit "Create Post" ,class: "btn btn-primary btn-lg"%>
	<% end %>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Post") %>
<div class="container" style="text-align:center;">
	<h1> <%= @post.content %> </h1>
</div>
<div class="container" style="text-align:center;">
	<% @post.blocks.each do |block| %>
	  <%= render block %>
	<% end %>
</div>

app/views/shared/_user_info.html.erb
<%= gravatar_for @user %>
<h1><%= @user.name %></h1>
<span><%= @user.email %></span>
<span><%= pluralize(@user.posts.count, "post") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="about-1">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<center><h1>We help to choose. Ya! We are good!</h1></center>
			</div>
		</div>
	</div>
</div>
<div id="about-para">
Whenever you are trapped in a dilemma, a confusion, you try to seek help of somebody. What if you can have the whole public help you decide. This portal lets you put up your dilemma on the cyberspace and the public will tell you, What you should <b>choose!</b>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">
<h1 align="center"> Contact the Developers </h1>
<p>
	<ul class="list-group">
	<li class="list-group-item"><b> Rounaq Jhunjhunu Wala </b><i>(CEO)</i> rounaq14089@iiitd.ac.in </li>
	<li class="list-group-item"><b> Nitin Kumar </b><i>(CFO)</i> nitin14069@iiitd.ac.in </li>
	<li class="list-group-item"><b> Sarthak Madan </b><i>(CTO)</i> sarthak14094@iiitd.ac.in </li>
	</ul>
</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron" style="text-align:center;">
  <% if !user_signed_in? %>
  <h1>Hi! There</h1>
  <h2>
  What do you want to choose today?
  </h2>
  <%= link_to "Sign up",new_registration_path(:user), class: "btn btn-lg btn-primary" %>
  <%= link_to "Log In",new_session_path(:user), class: "btn btn-lg btn-primary" %>
  </div>
  <% else %>
  	<% if current_user.sign_in_count==1 %>
		<h1>Hi <%= current_user.name %>, Welcome to HMC!</h1>
	<% else %>
		<h1>Welcome Back!</h1>
    <%= link_to "Create new Post",new_post_path(:user), class: "btn btn-lg btn-primary" %>
	<% end %>
	</div>
  <% end %>
<div class="container">
<% if @posts.count != 0 %>
  <h1> Recent Posts </h1>
  <ol class="microposts">
  <% @posts.each do |post| %>
 	<li id="post-<%= post.id %>">
  	<%= link_to gravatar_for(post.user, size: 50), post.user %>
  	<span class="user"><%= link_to post.user.name, post.user %></span>
  	<span class="content"><%= link_to post.content,post_path(post.id) %></span>
    <span class="timestamp">
   	 Posted <%= time_ago_in_words(post.created_at) %> ago.
   	 <% if current_user==post.user %>
    	  <%= link_to "delete", post, method: :delete,data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>
 <% end %>
</ol>
<% else %>
  <h3 style="color:#A0A0A0;">No Posts created</h3>
<% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
<div class="row">
<aside class="col-md-3">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <br/>
      <br/>
      <br/>
      <%= link_to "New Post", new_post_path, class: "btn btn-md btn-primary" %>
</aside>
<div class="col-md-9">
<% if @user.posts.any? %>
  <h3>Posts (<%= @user.posts.count %>)</h3>
  <ol class="microposts">
    <%= render @posts %>
  </ol>
  <%= will_paginate @posts %>
<% else %>
  <h3 style="color:#A0A0A0;">No Posts created</h3>
<% end %>
</div>
</div>
</div>